In [ ]:
'''   
    Importing the google drive on google colab
'''

from google.colab import drive
drive.mount('/drive')

In [ ]:
#Importing other libraries.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
import cv2

In [ ]:
# importing the dataset for training and testing.

df_train = pd.read_csv("/drive/My Drive/ML Data/mnist_train.csv")
df_test = pd.read_csv("/drive/My Drive/ML Data/mnist_test.csv")

df_train.head()

Droppin the Null values


```
# This is formatted as code
```



In [ ]:
print(df_train.shape)
print(df_test.shape)

# Dropping the rows with error values
train_new = df_train.dropna()
test_new = df_test.dropna()

print("New shapes : \n")
print(train_new.shape)
print(test_new.shape)


Clearly, none of the rows has an error value in it. 

EDA of the data set


In [ ]:
print(train_new.info())

train_new.describe()

In [ ]:
# Splitting the labels from the data

train = train_new.iloc[:,1:]
train_label = train_new.iloc[:,0]

test = test_new.iloc[:,1:]
test_label = test_new.iloc[:,0]

train.head()

In [ ]:
train_label.columns = ['label']
train_label.head()

In [ ]:
# Watching an image now

trial = train.iloc[69,:]
trial = trial.values.reshape(28, 28)
plt.imshow(trial, cmap='gray')

In [ ]:
# developing a countplot and displaying the count values

i = 0
for i in range(10):
  count = train_label.loc[train_label == i ]
  print("Value",i," : ", len(count))

sns.countplot(train_label)

In [ ]:
# data normalization and scaling

train = train/255
test = test/255

# Doubt - why scale now?

from sklearn.preprocessing import scale
train = scale(train)
test = scale(test)


In [ ]:
# linear model

model_linear = SVC(kernel='linear')
model_linear.fit(train, train_label)

# predict
y_pred = model_linear.predict(test)

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

'''
from sklearn.metrix import classification_report
print(classification_report(y_test, y_fit, target_label))
''''
# accuracy
print("accuracy:", metrics.accuracy_score(y_true=test_label, y_pred=y_pred), "\n")

cm = metrics.confusion_matrix(y_true = test_label, y_pred=y_pred)
# Printing the sensitivities

col_sum = cm.sum(axis = 0)
i = 0
for i in range(10):
  sens = cm[i,i] / col_sum[i]
  print("Sensitivity for",i,"is : ",round(sens, 3))  
print('\n')
print(cm)

accuracy: 0.928 

Sensitivity for 0 is :  0.939
Sensitivity for 1 is :  0.96
Sensitivity for 2 is :  0.898
Sensitivity for 3 is :  0.894
Sensitivity for 4 is :  0.92
Sensitivity for 5 is :  0.909
Sensitivity for 6 is :  0.96
Sensitivity for 7 is :  0.95
Sensitivity for 8 is :  0.913
Sensitivity for 9 is :  0.934


[[ 953    0    6    2    1    8    6    2    1    1]
 [   0 1118    7    2    0    1    2    1    4    0]
 [   9   12  956   11    9    4    5    5   18    3]
 [   7    1   15  940    0   17    1    6   19    4]
 [   3    2   18    1  927    0    3    6    3   19]
 [   7    6    7   40    5  791   12    1   20    3]
 [  14    3   17    1    9   19  892    0    3    0]
 [   2    8   23   14   11    2    0  945    2   21]
 [  11    7   10   29    8   23    8    6  860   12]
 [   9    7    6   11   38    5    0   23   12  898]]


In [ ]:
# Non linear model
from sklearn.model_selection import validation_curve
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV


folds = KFold(n_splits = 5, shuffle = True, random_state = 1)

# Set the parameters by cross-validation
hyper_params = [ {'gamma': [1e-1, 1e-2, 1e-3, 1e-4],
                     'C': [5,10]}]


# specify model
model = SVC(kernel="rbf")

# set up GridSearchCV()
model_cv = GridSearchCV(estimator = model, 
                        param_grid = hyper_params, 
                        scoring= 'accuracy', 
                        cv = folds, 
                        verbose = 1,
                        return_train_score=True)      

# fit the model
model_cv.fit(train, train_label)

In [ ]:
cv_results = pd.DataFrame(model_cv.cv_results_)
cv_results
cv_results['param_C'] = cv_results['param_C'].astype('int')

# # plotting
plt.figure(figsize=(16,10))

# subplot 1/4
plt.subplot(221)
gamma_01 = cv_results[cv_results['param_gamma']==0.1]

plt.plot(gamma_1["param_C"], gamma_1["mean_test_score"])
plt.plot(gamma_1["param_C"], gamma_1["mean_train_score"])
plt.xlabel('C')
plt.ylabel('Accuracy')
plt.title("Gamma=0.1")
plt.ylim([0.60, 1])
plt.legend(['test accuracy', 'train accuracy'], loc='upper left')
plt.xscale('log')

# subplot 2/4
plt.subplot(222)
gamma_01 = cv_results[cv_results['param_gamma']==0.01]

plt.plot(gamma_01["param_C"], gamma_01["mean_test_score"])
plt.plot(gamma_01["param_C"], gamma_01["mean_train_score"])
plt.xlabel('C')
plt.ylabel('Accuracy')
plt.title("Gamma=0.01")
plt.ylim([0.60, 1])
plt.legend(['test accuracy', 'train accuracy'], loc='upper left')
plt.xscale('log')

# subplot 3/4
plt.subplot(223)
gamma_01 = cv_results[cv_results['param_gamma']==0.001]

plt.plot(gamma_001["param_C"], gamma_001["mean_test_score"])
plt.plot(gamma_001["param_C"], gamma_001["mean_train_score"])
plt.xlabel('C')
plt.ylabel('Accuracy')
plt.title("Gamma=0.001")
plt.ylim([0.60, 1])
plt.legend(['test accuracy', 'train accuracy'], loc='upper left')
plt.xscale('log')

# subplot 4/4
plt.subplot(224)
gamma_01 = cv_results[cv_results['param_gamma']==0.0001]

plt.plot(gamma_0001["param_C"], gamma_0001["mean_test_score"])
plt.plot(gamma_0001["param_C"], gamma_0001["mean_train_score"])
plt.xlabel('C')
plt.ylabel('Accuracy')
plt.title("Gamma=0.0001")
plt.ylim([0.60, 1])
plt.legend(['test accuracy', 'train accuracy'], loc='upper left')
plt.xscale('log')


In [ ]:
#Modeling for best score

C_best = model_cv.best_score_
gamma_best = model_cv.best_params_


model = SVC(C=C_best, gamma=gamma_best, kernel="rbf")

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# metrics

print("accuracy", metrics.accuracy_score(y_test, y_pred), "\n")
print(metrics.confusion_matrix(y_test, y_pred), "\n")